export { default as Button } from './widget/Button.vue'
export { default as Input } from './widget/Input.vue'
export { default as Slider } from './widget/Slider.vue'
export { default as Text } from './widget/Text.vue'
export { default as Toggle } from './widget/Toggle.vue'
export { default as Icon } from './widget/Icon.vue'
